# Generated by Django 3.0.1 on 2019-12-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20191228_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapr',
            name='bi',
        ),
    ]
