# Generated by Django 3.0.1 on 2019-12-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('students', '0010_mapr_bi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkAndPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('presence', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='basic_info',
            new_name='Students',
        ),
        migrations.DeleteModel(
            name='mapr',
        ),
        migrations.AddField(
            model_name='markandpresence',
            name='bi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
    ]
