# Generated by Django 3.0.1 on 2019-12-31 09:28

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('students', '0011_auto_20191231_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markandpresence',
            old_name='bi',
            new_name='student',
        ),
    ]
