# Generated by Django 3.0.1 on 2019-12-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_mapr_bi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapr',
            name='bi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='students.basic_info'),
            preserve_default=False,
        ),
    ]
